Create Login and Register Pages
js-tasks-ru/vue-20201210_mell-hime pull request #9
Opened 2021-01-18 20:17 UTC by mellhime

2021-01-18 20:48 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
LoginPage и RegisterPage
+ LoginPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ LoginPage должен выводить "Требуется ввести пароль" при сабмите c email, но без введённого пароля
+ LoginPage должен выводить "Неверные учетные данные" при сабмите с неверными данными
+ LoginPage должен выводить полное имя при сабмите с верными данными
+ RegisterPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ RegisterPage должен выводить "Требуется ввести полное имя" при са��мите без полного имени
+ RegisterPage должен выводить "Требуется ввести пароль" при сабмите без пароля
+ RegisterPage должен выводить "Пароли не совпадают" при сабмите с несовпадающими паролями
+ RegisterPage должен выводить "Требуется согласиться с условиями" при сабмите без согласия
+ RegisterPage должен выводить ошибку при неуспешной регистрации
+ RegisterPage должен выводить ID пользователя при успешной регистрации
+ LoginPage должен рендериться на странице /login
+ RegisterPage должен рендериться на странице /register
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2021-01-18 21:45 UTC, ShGKme requested changes
Требуется поправить некорректное использование функции `data`

2021-01-18 21:45 UTC, ShGKme commented on 04-SPA/05-AuthPages/views/LoginPage.vue
> +      },
В `data` возвращается объект с реактивными свойствами компонента. Это те данные, которые будут реактивными данными компонента, а не их описание. Т.е. в такой записи в качестве значения объекта `user` с данными пользователя сохраняется объект без полей `email` или `password`, но с полем `type`.

2021-01-19 14:22 UTC, mellhime commented on 04-SPA/05-AuthPages/views/LoginPage.vue
> +      user: {},
или тут надо все поля расписывать? Не очень понятно

2021-01-19 14:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
LoginPage и RegisterPage
+ LoginPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ LoginPage должен выводить "Требуется ввести пароль" при сабмите c email, но без введённого пароля
+ LoginPage должен выводить "Неверные учетные данные" при сабмите с неверными данными
+ LoginPage должен выводить полное имя при сабмите с верными данными
+ RegisterPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ RegisterPage должен выводить "Требуется ввести полное имя" при са��мите без полного имени
+ RegisterPage должен выводить "Требуется ввести пароль" при сабмите без пароля
+ RegisterPage должен выводить "Пароли не совпадают" при сабмите с несовпадающими паролями
+ RegisterPage должен выводить "Требуется согласиться с условиями" при сабмите без согласия
+ RegisterPage должен выводить ошибку при неуспешной регистрации
+ RegisterPage должен выводить ID пользователя при успешной регистрации
+ LoginPage должен рендериться на странице /login
+ RegisterPage должен рендериться на странице /register
```
```diff
Работа с query параметрами
- Значение параметров должно соответствовать значениям query параметров в маршруте
- При изменении значения параметров должен меняться маршрут (push или query)
- При переходе на маршрут с другим query, должно обновлять соответствующие параметры
- Если какой-то параметр меняется на значение по умолчанию, его не должно быть в query
```

2021-01-20 16:50 UTC, ShGKme requested changes
Требуется полностью инициализировать данные компонента

2021-01-20 16:50 UTC, ShGKme commented on 04-SPA/05-AuthPages/views/LoginPage.vue
> +      user: {},
Краткий ответ, да, требуется описать каждое используемое поле.

Как и в ещё первых задачах с выводом данных митапа, не хорошо инициализировать объект просто пустым объектом `{}`. Пустой объект - не частный случай объекта с данными митапа, не начальные данные. 

Такая инициализация может быть уместна, если объект - это некоторый словарь, который позволит потом находить значения по ключу (например, митапы по ID или по дате), то есть который используется, как структура данных для хранения и доступа к данным.

Важно также помнить ограничения реактивности. Vue делает объект реактивным на этапе инициализации, проходя по всем полям объекта, и устанавливая им геттер и сеттер. В данном случае в объекте нет полей. Появившиеся позже поля `user.email` и другие не будут реактивными.

2021-01-27 08:34 UTC, mellhime commented on 04-SPA/06-Query/views/PageWithQuery.vue
> +    search: function (oldValue, newValue) {
вот здесь я пытаюсь отслеживать изменение параметра search, и делать маршрут с его новым значением, но изменение маршрута попадает под отслеживание параметра $route выше, и получается рекурсия

2021-01-27 14:29 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2021-01-28 19:38 UTC, mellhime commented on 04-SPA/06-Query/views/PageWithQuery.vue
> +        return null;
А что здесь лучше вернуть? нам не нужен геттер этого свойства в этом случае

2021-01-28 20:40 UTC, ShGKme commented on 04-SPA/06-Query/views/PageWithQuery.vue
> +        return null;
`updatedQuery` вам на самом деле не нужен. Можно сразу присваивать новые значения в `pageAttrs` без использования посредника в виде `updatedQuery set`.

2021-01-28 20:45 UTC, ShGKme requested changes
Вычисляемое свойство получилось совсем бесполезным.
Кроме того, если в `$query` значение отсутствует, то в `pageAttrs` также не попадает никакое значение. Требуется, при отсутствии значения, устанавливать значение по умолчанию. Предлагается сделать небольшое исправление.

2021-01-29 10:21 UTC, ShGKme approved these changes
Принято

2021-02-01 19:18 UTC, merged